server:
  port: 80

spring:
  application:
    name: 'restaurant_service'
  datasource:
    username: 'postgres'
    password: 'dek-IT2077'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/javalab'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true: true

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:9000/eureka'
  instance:
    prefer-ip-address: true